-- Criação do Banco de Dados
CREATE DATABASE agencia_viagens;
USE agencia_viagens;

-- 1. Tabela VENDEDOR
CREATE TABLE VENDEDOR (
    Matricula VARCHAR(10) NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (Matricula)
);

-- 2. Tabela VENDA
CREATE TABLE VENDA (
    id_Venda INT AUTO_INCREMENT NOT NULL,
    Data DATE NOT NULL,
    Valor_Total DECIMAL(10,2) NOT NULL,
    Matricula_Vendedor VARCHAR(10) NOT NULL,
    Nome_Cliente VARCHAR(100) NOT NULL,
    CONSTRAINT PK_VENDA PRIMARY KEY (id_Venda),
    CONSTRAINT FK_VENDA_VENDEDOR FOREIGN KEY (Matricula_Vendedor) 
        REFERENCES VENDEDOR(Matricula) ON DELETE RESTRICT
);

-- 3. Tabela COMISSAO
CREATE TABLE COMISSAO (
    id_Comissao INT AUTO_INCREMENT NOT NULL,
    Valor_Bonificacao DECIMAL(10,2) NOT NULL,
    id_Venda INT NOT NULL,
    CONSTRAINT PK_COMISSAO PRIMARY KEY (id_Comissao),
    CONSTRAINT FK_COMISSAO_VENDA FOREIGN KEY (id_Venda) 
        REFERENCES VENDA(id_Venda) ON DELETE CASCADE
);

-- 4. Tabela RECEBIMENTO
CREATE TABLE RECEBIMENTO (
    id_Recebimento INT AUTO_INCREMENT NOT NULL,
    Metodo VARCHAR(50) NOT NULL,
    Valor DECIMAL(10,2) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Pendente' NOT NULL,
    id_Venda INT NOT NULL,
    CONSTRAINT PK_RECEBIMENTO PRIMARY KEY (id_Recebimento),
    CONSTRAINT FK_RECEBIMENTO_VENDA FOREIGN KEY (id_Venda) 
        REFERENCES VENDA(id_Venda) ON DELETE RESTRICT
);

-- 5. Tabela FORNECEDOR
CREATE TABLE FORNECEDOR (
    CNPJ VARCHAR(14) NOT NULL,
    Nome_Fantasia VARCHAR(100) NOT NULL,
    Contato VARCHAR(100),
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY (CNPJ),
    CONSTRAINT UC_FORNECEDOR_CNPJ UNIQUE (CNPJ)
);

-- 6. Tabela PAGAMENTO_FORNECEDOR
CREATE TABLE PAGAMENTO_FORNECEDOR (
    id_Pagamento INT AUTO_INCREMENT NOT NULL,
    Valor_Custo_Produto DECIMAL(10,2) NOT NULL,
    Data_Limite_Pagamento DATE NOT NULL,
    id_Venda INT NOT NULL,
    CNPJ_Fornecedor VARCHAR(14) NOT NULL,
    CONSTRAINT PK_PAGAMENTO_FORNECEDOR PRIMARY KEY (id_Pagamento),
    CONSTRAINT FK_PAG_VENDA FOREIGN KEY (id_Venda) 
        REFERENCES VENDA(id_Venda) ON DELETE RESTRICT,
    CONSTRAINT FK_PAG_FORNECEDOR FOREIGN KEY (CNPJ_Fornecedor) 
        REFERENCES FORNECEDOR(CNPJ) ON DELETE RESTRICT
);

-- 7. Tabela PACOTE
CREATE TABLE PACOTE (
    id_Pacote INT AUTO_INCREMENT NOT NULL,
    Descricao VARCHAR(255) NOT NULL,
    Preco_Venda DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_PACOTE PRIMARY KEY (id_Pacote)
);

-- 8. Tabela SERVICO
CREATE TABLE SERVICO (
    id_Servico INT AUTO_INCREMENT NOT NULL,
    Descricao VARCHAR(255) NOT NULL,
    Categoria VARCHAR(50),
    CONSTRAINT PK_SERVICO PRIMARY KEY (id_Servico)
);

-- 9. Tabela Associativa PACOTE_SERVICO
CREATE TABLE PACOTE_SERVICO (
    id_Pacote INT NOT NULL,
    id_Servico INT NOT NULL,
    CONSTRAINT PK_PACOTE_SERVICO PRIMARY KEY (id_Pacote, id_Servico),
    CONSTRAINT FK_PS_PACOTE FOREIGN KEY (id_Pacote) 
        REFERENCES PACOTE(id_Pacote) ON DELETE CASCADE,
    CONSTRAINT FK_PS_SERVICO FOREIGN KEY (id_Servico) 
        REFERENCES SERVICO(id_Servico) ON DELETE RESTRICT
);